import { useRef,useState } from 'react';
import { Alert,Image,Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { CameraView,useCameraPermissions } from 'expo-camera';
import { router } from 'expo-router';
import { discoveries } from '../data/mock';
import { searchGermanCards } from '../services/tcgdex';
import TextRecognition from '@infinitered/react-native-mlkit-text-recognition';

type Mode='card'|'sealed';
export default function ScannerScreen(){
 const[permission,requestPermission]=useCameraPermissions();
 const[mode,setMode]=useState<Mode>('card');
 const[locked,setLocked]=useState(false);const[code,setCode]=useState('');const[photo,setPhoto]=useState('');const[recognizing,setRecognizing]=useState(false);
 const camera=useRef<CameraView|null>(null);
 if(!permission)return <SafeAreaView style={s.safe}/>;
 if(!permission.granted)return <SafeAreaView style={s.safe}><View style={s.permission}><Text style={s.title}>Kamera freigeben</Text><Text style={s.copy}>Sammelfolio benötigt die Kamera, damit du Karten fotografieren und Barcodes von Sealed-Produkten scannen kannst.</Text><Pressable style={s.primary} onPress={requestPermission}><Text style={s.primaryText}>Kamera erlauben</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.back}>Zurück</Text></Pressable></View></SafeAreaView>;
 const scanned=({data}:{data:string})=>{if(mode!=='sealed'||locked)return;setLocked(true);setCode(data);const product=discoveries.find((x:any)=>x.barcode===data||x.ean===data||x.upc===data);if(product){router.replace({pathname:'/item/[id]',params:{id:product.id}});return}Alert.alert('Barcode erkannt',`${data}\n\nDieser Barcode ist noch keinem Produkt in Sammelfolio zugeordnet.`,[{text:'Erneut scannen',onPress:()=>{setLocked(false);setCode('')}},{text:'Produkt anlegen',onPress:()=>router.replace({pathname:'/manual-product',params:{barcode:data}})}])};
 const recognizeCard=async(uri:string)=>{try{setRecognizing(true);const result=await TextRecognition.recognize(uri);const text=result.text||'';const lines=text.split(/\n/).map(x=>x.trim()).filter(Boolean);const numberMatch=text.match(/(?:#\s*)?(\d{1,3})\s*\/\s*(\d{1,3})/);const ignored=/^(basic|stage|hp\s*\d+|trainer|energy|pokemon|pokémon)$/i;const names=lines.filter(x=>x.length>=3&&x.length<=32&&!ignored.test(x)&&!/^\d/.test(x)&&!x.includes('/'));
   let matches:any[]=[];for(const name of names.slice(0,5)){const found=await searchGermanCards(name);if(found.length){matches=found;break}}
   if(numberMatch&&matches.length){const local=String(Number(numberMatch[1]));const exact=matches.find(c=>String(Number(c.localId))===local);if(exact){router.replace({pathname:'/card/[id]',params:{id:exact.id}});return}}
   if(matches.length===1){router.replace({pathname:'/card/[id]',params:{id:matches[0].id}});return}
   if(matches.length>1){Alert.alert('Karte erkannt',`${matches[0].name}${numberMatch?` · #${numberMatch[1]}/${numberMatch[2]}`:''}\n\nEs gibt mehrere mögliche Treffer. Öffne die Suche und wähle die richtige Karte.`,[{text:'Neu scannen',onPress:()=>setPhoto('')},{text:'Treffer prüfen',onPress:()=>router.replace({pathname:'/(tabs)/discover',params:{q:matches[0].name}})}]);return}
   Alert.alert('Karte nicht eindeutig erkannt','Versuche es erneut bei gutem Licht, ohne Spiegelung und mit der gesamten Karte im Rahmen.',[{text:'Erneut scannen',onPress:()=>setPhoto('')},{text:'Manuell suchen',onPress:()=>router.replace('/(tabs)/discover')}])
 }catch{Alert.alert('Erkennung fehlgeschlagen','Die Karte konnte nicht gelesen werden. Für die Texterkennung ist ein Development Build der App erforderlich.',[{text:'Erneut versuchen',onPress:()=>setPhoto('')},{text:'Kartensuche',onPress:()=>router.replace('/(tabs)/discover')}])}finally{setRecognizing(false)}};
 const photograph=async()=>{try{const shot=await camera.current?.takePictureAsync({quality:1,skipProcessing:false});if(!shot?.uri)return;setPhoto(shot.uri);await recognizeCard(shot.uri)}catch{Alert.alert('Kamera','Das Foto konnte nicht aufgenommen werden.')}};
 const switchMode=(next:Mode)=>{setMode(next);setLocked(false);setCode('');setPhoto('')};
 return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Zurück</Text></Pressable><Text style={s.title}>Scannen</Text><View style={s.tabs}><Pressable onPress={()=>switchMode('card')} style={[s.tab,mode==='card'&&s.tabOn]}><Text style={[s.tabText,mode==='card'&&s.tabTextOn]}>Karte</Text></Pressable><Pressable onPress={()=>switchMode('sealed')} style={[s.tab,mode==='sealed'&&s.tabOn]}><Text style={[s.tabText,mode==='sealed'&&s.tabTextOn]}>Sealed</Text></Pressable></View><Text style={s.copy}>{mode==='card'?'Lege die Karte gerade und vollständig in den Rahmen. Sammelfolio liest Name und Kartennummer und gleicht sie mit dem deutschen Kartenkatalog ab.':'Halte den Barcode einer TTB, eines Displays, Booster Bundles, einer Tin oder Kollektion in den Rahmen.'}</Text></View><View style={s.cameraWrap}>{photo&&mode==='card'?<Image source={{uri:photo}} style={s.camera}/>:<CameraView ref={camera} style={s.camera} facing="back" barcodeScannerSettings={mode==='sealed'?{barcodeTypes:['ean13','ean8','upc_a','upc_e','code128']}:undefined} onBarcodeScanned={mode==='sealed'&&!locked?scanned:undefined}/>}<View pointerEvents="none" style={[s.frame,mode==='card'&&s.cardFrame]}/></View><View style={s.bottom}>{mode==='card'?<><Pressable disabled={recognizing} style={[s.capture,recognizing&&{opacity:.45}]} onPress={photo?()=>setPhoto(''):photograph}><View style={s.captureInner}/></Pressable><Text style={s.status}>{recognizing?'Karte wird erkannt …':photo?'Foto aufgenommen':'Karte scannen'}</Text><Text style={s.note}>Name und Kartennummer werden auf dem Gerät gelesen und anschließend mit TCGdex abgeglichen. Bei mehreren Treffern lässt Sammelfolio dich die richtige Karte bestätigen.</Text></>:<><Text style={s.status}>{code?`Erkannt: ${code}`:'Bereit zum Barcode-Scan'}</Text>{locked?<Pressable style={s.primary} onPress={()=>{setLocked(false);setCode('')}}><Text style={s.primaryText}>Erneut scannen</Text></Pressable>:null}<Text style={s.note}>Der Barcode wird direkt gelesen. Ist die EAN/UPC im Sammelfolio-Katalog hinterlegt, öffnet sich automatisch das passende Produkt.</Text></>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#050914'},header:{padding:20,paddingBottom:14},back:{color:'#72DDF1',fontWeight:'900',marginBottom:12},title:{color:'#F7F9FF',fontSize:27,fontWeight:'900'},copy:{color:'#8490A8',lineHeight:19,marginTop:10},tabs:{flexDirection:'row',backgroundColor:'#0A1222',borderRadius:14,padding:4,marginTop:14},tab:{flex:1,paddingVertical:10,alignItems:'center',borderRadius:11},tabOn:{backgroundColor:'#635BDF'},tabText:{color:'#7E8AA2',fontWeight:'900'},tabTextOn:{color:'#FFF'},cameraWrap:{flex:1,marginHorizontal:18,borderRadius:24,overflow:'hidden',borderWidth:1,borderColor:'#263A60'},camera:{flex:1,width:'100%',height:'100%'},frame:{position:'absolute',left:'10%',right:'10%',top:'35%',height:130,borderWidth:3,borderColor:'#70DFF2',borderRadius:18},cardFrame:{left:'18%',right:'18%',top:'10%',height:'80%',borderRadius:22},bottom:{padding:18,alignItems:'center'},status:{color:'#F4F7FF',fontWeight:'900',textAlign:'center',marginTop:8},note:{color:'#74819A',fontSize:10,lineHeight:15,textAlign:'center',marginTop:10},permission:{flex:1,justifyContent:'center',padding:24},primary:{backgroundColor:'#635BDF',borderRadius:15,padding:15,alignItems:'center',marginTop:12,width:'100%'},primaryText:{color:'#FFF',fontWeight:'900'},capture:{width:66,height:66,borderRadius:33,borderWidth:4,borderColor:'#F7F9FF',alignItems:'center',justifyContent:'center'},captureInner:{width:48,height:48,borderRadius:24,backgroundColor:'#F7F9FF'}});