import { useState } from 'react';
import { Alert,Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { CameraView,useCameraPermissions } from 'expo-camera';
import { router } from 'expo-router';
import { discoveries } from '../data/mock';

export default function ScannerScreen(){
 const[permission,requestPermission]=useCameraPermissions();
 const[locked,setLocked]=useState(false);
 const[code,setCode]=useState('');
 if(!permission)return <SafeAreaView style={s.safe}/>;
 if(!permission.granted)return <SafeAreaView style={s.safe}><View style={s.permission}><Text style={s.title}>Kamera freigeben</Text><Text style={s.copy}>Sammelfolio benötigt die Kamera, um EAN- und UPC-Barcodes von Sealed-Produkten zu lesen.</Text><Pressable style={s.primary} onPress={requestPermission}><Text style={s.primaryText}>Kamera erlauben</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.back}>Zurück</Text></Pressable></View></SafeAreaView>;
 const scanned=({data}:{data:string})=>{if(locked)return;setLocked(true);setCode(data);const product=discoveries.find((x:any)=>x.barcode===data||x.ean===data||x.upc===data);if(product){router.replace({pathname:'/item/[id]',params:{id:product.id}});return}Alert.alert('Barcode erkannt',`${data}\n\nDieser Barcode ist noch keinem Produkt in Sammelfolio zugeordnet.`,[{text:'Erneut scannen',onPress:()=>{setLocked(false);setCode('')}},{text:'Produkt anlegen',onPress:()=>router.replace({pathname:'/manual-product',params:{barcode:data}})}])};
 return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Zurück</Text></Pressable><Text style={s.title}>Sealed scannen</Text><Text style={s.copy}>Halte den Barcode einer TTB, eines Displays, Booster Bundles, einer Tin oder Kollektion in den Rahmen.</Text></View><View style={s.cameraWrap}><CameraView style={s.camera} facing="back" barcodeScannerSettings={{barcodeTypes:['ean13','ean8','upc_a','upc_e','code128']}} onBarcodeScanned={locked?undefined:scanned}/><View pointerEvents="none" style={s.frame}/></View><View style={s.bottom}><Text style={s.status}>{code?`Erkannt: ${code}`:'Bereit zum Scannen'}</Text>{locked?<Pressable style={s.primary} onPress={()=>{setLocked(false);setCode('')}}><Text style={s.primaryText}>Erneut scannen</Text></Pressable>:null}<Text style={s.note}>Der Scanner liest den echten Barcode. Automatisch öffnen kann Sammelfolio ein Produkt, sobald dessen EAN/UPC im Produktkatalog hinterlegt ist.</Text></View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#050914'},header:{padding:20,paddingBottom:14},back:{color:'#72DDF1',fontWeight:'900',marginBottom:14},title:{color:'#F7F9FF',fontSize:27,fontWeight:'900'},copy:{color:'#8490A8',lineHeight:19,marginTop:7},cameraWrap:{flex:1,marginHorizontal:18,borderRadius:24,overflow:'hidden',borderWidth:1,borderColor:'#263A60'},camera:{flex:1},frame:{position:'absolute',left:'10%',right:'10%',top:'35%',height:130,borderWidth:3,borderColor:'#70DFF2',borderRadius:18},bottom:{padding:20},status:{color:'#F4F7FF',fontWeight:'900',textAlign:'center',marginBottom:12},note:{color:'#74819A',fontSize:10,lineHeight:15,textAlign:'center',marginTop:12},permission:{flex:1,justifyContent:'center',padding:24},primary:{backgroundColor:'#635BDF',borderRadius:15,padding:15,alignItems:'center',marginTop:18},primaryText:{color:'#FFF',fontWeight:'900'}});