import { useRef,useState } from 'react';
import { Alert,Image,Pressable,SafeAreaView,StyleSheet,Text,View } from 'react-native';
import { CameraView,useCameraPermissions } from 'expo-camera';
import { router } from 'expo-router';
import { discoveries } from '../data/mock';

type Mode='card'|'sealed';
export default function ScannerScreen(){
 const[permission,requestPermission]=useCameraPermissions();
 const[mode,setMode]=useState<Mode>('card');
 const[locked,setLocked]=useState(false);const[code,setCode]=useState('');const[photo,setPhoto]=useState('');
 const camera=useRef<CameraView|null>(null);
 if(!permission)return <SafeAreaView style={s.safe}/>;
 if(!permission.granted)return <SafeAreaView style={s.safe}><View style={s.permission}><Text style={s.title}>Kamera freigeben</Text><Text style={s.copy}>Sammelfolio benötigt die Kamera, damit du Karten fotografieren und Barcodes von Sealed-Produkten scannen kannst.</Text><Pressable style={s.primary} onPress={requestPermission}><Text style={s.primaryText}>Kamera erlauben</Text></Pressable><Pressable onPress={()=>router.back()}><Text style={s.back}>Zurück</Text></Pressable></View></SafeAreaView>;
 const scanned=({data}:{data:string})=>{if(mode!=='sealed'||locked)return;setLocked(true);setCode(data);const product=discoveries.find((x:any)=>x.barcode===data||x.ean===data||x.upc===data);if(product){router.replace({pathname:'/item/[id]',params:{id:product.id}});return}Alert.alert('Barcode erkannt',`${data}\n\nDieser Barcode ist noch keinem Produkt in Sammelfolio zugeordnet.`,[{text:'Erneut scannen',onPress:()=>{setLocked(false);setCode('')}},{text:'Produkt anlegen',onPress:()=>router.replace({pathname:'/manual-product',params:{barcode:data}})}])};
 const photograph=async()=>{try{const shot=await camera.current?.takePictureAsync({quality:.8});if(!shot?.uri)return;setPhoto(shot.uri);Alert.alert('Karte fotografiert','Die Aufnahme ist bereit. Die automatische Kartenerkennung per Bild benötigt noch den Matching-Dienst. Bis dahin kannst du direkt zur Kartensuche wechseln.',[{text:'Neu fotografieren',onPress:()=>setPhoto('')},{text:'Kartensuche öffnen',onPress:()=>router.replace('/(tabs)/discover')}])}catch{Alert.alert('Kamera','Das Foto konnte nicht aufgenommen werden.')}};
 const switchMode=(next:Mode)=>{setMode(next);setLocked(false);setCode('');setPhoto('')};
 return <SafeAreaView style={s.safe}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Zurück</Text></Pressable><Text style={s.title}>Scannen</Text><View style={s.tabs}><Pressable onPress={()=>switchMode('card')} style={[s.tab,mode==='card'&&s.tabOn]}><Text style={[s.tabText,mode==='card'&&s.tabTextOn]}>Karte</Text></Pressable><Pressable onPress={()=>switchMode('sealed')} style={[s.tab,mode==='sealed'&&s.tabOn]}><Text style={[s.tabText,mode==='sealed'&&s.tabTextOn]}>Sealed</Text></Pressable></View><Text style={s.copy}>{mode==='card'?'Lege die Karte möglichst gerade und vollständig in den Rahmen und fotografiere die Vorderseite.':'Halte den Barcode einer TTB, eines Displays, Booster Bundles, einer Tin oder Kollektion in den Rahmen.'}</Text></View><View style={s.cameraWrap}>{photo&&mode==='card'?<Image source={{uri:photo}} style={s.camera}/>:<CameraView ref={camera} style={s.camera} facing="back" barcodeScannerSettings={mode==='sealed'?{barcodeTypes:['ean13','ean8','upc_a','upc_e','code128']}:undefined} onBarcodeScanned={mode==='sealed'&&!locked?scanned:undefined}/>}<View pointerEvents="none" style={[s.frame,mode==='card'&&s.cardFrame]}/></View><View style={s.bottom}>{mode==='card'?<><Pressable style={s.capture} onPress={photo?()=>setPhoto(''):photograph}><View style={s.captureInner}/></Pressable><Text style={s.status}>{photo?'Foto aufgenommen · antippen für neues Foto':'Karte fotografieren'}</Text><Text style={s.note}>Der Kamera-Modus ist echt. Für die automatische Zuordnung des Fotos zu einer konkreten Pokémon-Karte wird als nächster Schritt ein Bilderkennungs-/Matching-Dienst angebunden.</Text></>:<><Text style={s.status}>{code?`Erkannt: ${code}`:'Bereit zum Barcode-Scan'}</Text>{locked?<Pressable style={s.primary} onPress={()=>{setLocked(false);setCode('')}}><Text style={s.primaryText}>Erneut scannen</Text></Pressable>:null}<Text style={s.note}>Der Barcode wird direkt gelesen. Ist die EAN/UPC im Sammelfolio-Katalog hinterlegt, öffnet sich automatisch das passende Produkt.</Text></>}</View></SafeAreaView>
}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:'#050914'},header:{padding:20,paddingBottom:14},back:{color:'#72DFF1',fontWeight:'900',marginBottom:12},title:{color:'#F7F9FF',fontSize:27,fontWeight:'900'},copy:{color:'#8490A8',lineHeight:19,marginTop:10},tabs:{flexDirection:'row',backgroundColor:'#0A1222',borderRadius:14,padding:4,marginTop:14},tab:{flex:1,paddingVertical:10,alignItems:'center',borderRadius:11},tabOn:{backgroundColor:'#635BDF'},tabText:{color:'#7E8AA2',fontWeight:'900'},tabTextOn:{color:'#FFF'},cameraWrap:{flex:1,marginHorizontal:18,borderRadius:24,overflow:'hidden',borderWidth:1,borderColor:'#263A60'},camera:{flex:1,width:'100%',height:'100%'},frame:{position:'absolute',left:'10%',right:'10%',top:'35%',height:130,borderWidth:3,borderColor:'#70DFF2',borderRadius:18},cardFrame:{left:'18%',right:'18%',top:'10%',height:'80%',borderRadius:22},bottom:{padding:18,alignItems:'center'},status:{color:'#F4F7FF',fontWeight:'900',textAlign:'center',marginTop:8},note:{color:'#74819A',fontSize:10,lineHeight:15,textAlign:'center',marginTop:10},permission:{flex:1,justifyContent:'center',padding:24},primary:{backgroundColor:'#635BDF',borderRadius:15,padding:15,alignItems:'center',marginTop:12,width:'100%'},primaryText:{color:'#FFF',fontWeight:'900'},capture:{width:66,height:66,borderRadius:33,borderWidth:4,borderColor:'#F7F9FF',alignItems:'center',justifyContent:'center'},captureInner:{width:48,height:48,borderRadius:24,backgroundColor:'#F7F9FF'}});