import { useEffect, useMemo, useState } from 'react';
import { ActivityIndicator, Image, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { discoveries, euro } from '../../data/mock';
import { cardImage, searchGermanCards, TCGdexCardBrief } from '../../services/tcgdex';

const productTypes = ['Alle', 'Top-Trainer-Box', 'Booster Bundle', 'Display'] as const;
type ProductFilter = typeof productTypes[number];

export default function DiscoverScreen() {
  const [query,setQuery]=useState(''); const [cards,setCards]=useState<TCGdexCardBrief[]>([]); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [productFilter,setProductFilter]=useState<ProductFilter>('Alle');
  useEffect(()=>{const value=query.trim(); if(value.length<2){setCards([]);setError('');return;} const timer=setTimeout(async()=>{try{setLoading(true);setError('');setCards(await searchGermanCards(value));}catch{setError('Kartensuche gerade nicht erreichbar.');}finally{setLoading(false);}},350); return()=>clearTimeout(timer);},[query]);
  const normalized=query.trim().toLowerCase();
  const sealed=useMemo(()=>discoveries.filter(item=>item.kind==='Sealed'&&(!normalized||`${item.name} ${item.subtitle} ${item.productType??''}`.toLowerCase().includes(normalized))&&(productFilter==='Alle'||item.productType===productFilter)),[normalized,productFilter]);
  const quick=['Glurak','Pikachu','151','Prismatische Entwicklungen'];

  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container} keyboardShouldPersistTaps="handled">
    <Text style={styles.kicker}>SAMMELN · VERWALTEN · ENTDECKEN</Text><Text style={styles.title}>Entdecken</Text><Text style={styles.subtitle}>Deutsche Einzelkarten live finden und Sealed-Produkte direkt verwalten.</Text>
    <TextInput value={query} onChangeText={setQuery} placeholder="Karte, Set, TTB, Bundle oder Display" placeholderTextColor="#64718B" style={styles.search} autoCorrect={false}/>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.quick}>{quick.map(item=><Pressable key={item} onPress={()=>setQuery(item)} style={styles.quickChip}><Text style={styles.quickText}>{item}</Text></Pressable>)}</ScrollView>
    {loading&&<ActivityIndicator style={styles.loader}/>} {!!error&&<Text style={styles.error}>{error}</Text>}
    {query.trim().length>=2&&<Text style={styles.section}>Einzelkarten</Text>}
    {query.trim().length>=2&&cards.length===0&&!loading&&!error?<Text style={styles.noResult}>Keine deutschen Karten gefunden.</Text>:cards.map(card=><Pressable key={card.id} style={styles.card} onPress={()=>router.push({pathname:'/card/[id]',params:{id:card.id}})}>{card.image?<Image source={{uri:cardImage(card.image)}} style={styles.image}/>:<View style={styles.cardIcon}><Text style={styles.cardIconText}>CARD</Text></View>}<View style={styles.main}><Text style={styles.name}>{card.name}</Text><Text style={styles.meta}>#{card.localId} · Deutsch</Text></View><Text style={styles.chevron}>›</Text></Pressable>)}
    <View style={styles.sectionRow}><Text style={styles.section}>Sealed-Produkte</Text><Text style={styles.sectionCount}>{sealed.length}</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{productTypes.map(type=><Pressable key={type} onPress={()=>setProductFilter(type)} style={[styles.filter,productFilter===type&&styles.filterActive]}><Text style={[styles.filterText,productFilter===type&&styles.filterTextActive]}>{type==='Top-Trainer-Box'?'TTB':type}</Text></Pressable>)}</ScrollView>
    {sealed.map(item=><Pressable key={item.id} style={styles.card} onPress={()=>router.push({pathname:'/item/[id]',params:{id:item.id}})}><View style={[styles.sealedIcon,item.productType==='Display'&&styles.displayIcon]}><View style={styles.boxTop}/><Text style={styles.sealedText}>{item.productType==='Top-Trainer-Box'?'TTB':item.productType==='Booster Bundle'?'BUNDLE':item.productType==='Display'?'DISPLAY':'SEALED'}</Text></View><View style={styles.main}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.setName??item.subtitle} · Deutsch</Text></View><View style={styles.priceBlock}><Text style={styles.price}>{euro(item.marketPrice)}</Text><Text style={styles.manual}>manuell</Text></View></Pressable>)}
    <View style={styles.info}><Text style={styles.infoTitle}>So funktioniert Sealed</Text><Text style={styles.infoText}>Du pflegst den Marktwert selbst. Sammelfolio speichert jeden Tagespreis und baut daraus deinen Preisverlauf.</Text></View>
  </ScrollView></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#050914'},container:{padding:20,paddingBottom:38},kicker:{color:'#66DCF1',fontSize:9,fontWeight:'900',letterSpacing:1.25},title:{color:'#F7F9FF',fontSize:30,fontWeight:'900',marginTop:5},subtitle:{color:'#74819A',marginTop:4,marginBottom:16,lineHeight:19},search:{backgroundColor:'#0A1222',borderRadius:16,borderWidth:1,borderColor:'#1E3153',paddingHorizontal:15,paddingVertical:14,color:'#F6F8FF'},quick:{gap:8,paddingVertical:10},quickChip:{backgroundColor:'#0B1528',borderWidth:1,borderColor:'#243B63',paddingVertical:7,paddingHorizontal:11,borderRadius:999},quickText:{color:'#91A2C3',fontSize:11,fontWeight:'800'},loader:{marginVertical:12},error:{color:'#FF8E9F',marginBottom:12},sectionRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},section:{color:'#8CDFF1',fontSize:11,fontWeight:'900',letterSpacing:1.1,marginTop:15,marginBottom:10,textTransform:'uppercase'},sectionCount:{color:'#66758E',fontSize:11,fontWeight:'800',marginTop:15},filters:{gap:8,paddingBottom:12},filter:{paddingHorizontal:12,paddingVertical:8,borderRadius:999,backgroundColor:'#0A1222',borderWidth:1,borderColor:'#1D2C4A'},filterActive:{backgroundColor:'#172D4D',borderColor:'#50CDEB'},filterText:{color:'#8793AA',fontWeight:'800',fontSize:11},filterTextActive:{color:'#7FE4F5'},card:{backgroundColor:'#09111F',borderRadius:18,padding:12,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#192743',marginBottom:10},image:{width:49,height:69,borderRadius:7,backgroundColor:'#17233B'},cardIcon:{width:52,height:62,borderRadius:9,borderWidth:1,borderColor:'#2B4C76',alignItems:'center',justifyContent:'center',backgroundColor:'#0E1B31'},cardIconText:{color:'#75DDF1',fontSize:8,fontWeight:'900'},sealedIcon:{width:58,height:54,borderRadius:10,borderWidth:2,borderColor:'#8B5CF6',backgroundColor:'#11152B',alignItems:'center',justifyContent:'center',overflow:'hidden'},displayIcon:{borderColor:'#B05BFF'},boxTop:{position:'absolute',top:4,width:35,height:7,borderBottomWidth:1,borderColor:'#D07BFF',opacity:.8},sealedText:{color:'#C695FF',fontSize:8,fontWeight:'900'},main:{flex:1,paddingHorizontal:12},name:{color:'#F2F5FF',fontSize:14,fontWeight:'900'},meta:{color:'#74819A',fontSize:11,marginTop:4},priceBlock:{alignItems:'flex-end'},price:{color:'#F2F5FF',fontWeight:'900',fontSize:13},manual:{color:'#7E6AA6',fontSize:9,marginTop:3},chevron:{color:'#70DFF2',fontSize:28},noResult:{color:'#6E7C95',fontSize:12,marginBottom:8},info:{marginTop:10,backgroundColor:'#0B1325',borderRadius:18,borderWidth:1,borderColor:'#21305A',padding:16},infoTitle:{color:'#EDF2FF',fontWeight:'900',fontSize:14},infoText:{color:'#74819A',fontSize:11,lineHeight:17,marginTop:5}});