import { SafeAreaView, ScrollView, StyleSheet, Text, View } from 'react-native';
import { euro } from '../../data/mock';
import { useWishlist } from '../../store/wishlist';

export default function WishlistScreen() {
  const { items } = useWishlist();
  const total = items.reduce((sum,item)=>sum+(item.marketPrice??0),0);
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
    <Text style={styles.kicker}>DEIN SAMMELFOLIO</Text><Text style={styles.title}>Wünsche</Text><Text style={styles.subtitle}>Alles, was als Nächstes in deine Sammlung soll.</Text>
    <View style={styles.summary}><View><Text style={styles.summaryLabel}>VORGEMERKT</Text><Text style={styles.summaryValue}>{items.length}</Text></View><View><Text style={styles.summaryLabel}>AKTUELLER WERT</Text><Text style={styles.summaryPrice}>{euro(total)}</Text></View></View>
    {items.length===0?<View style={styles.empty}><Text style={styles.heart}>♡</Text><Text style={styles.emptyTitle}>Noch nichts vorgemerkt</Text><Text style={styles.emptyText}>Öffne eine Karte oder ein Sealed-Produkt in Entdecken und füge es deiner Wunschliste hinzu.</Text></View>:items.map(item=><View key={item.id} style={styles.card}><View style={[styles.badge,item.kind==='Sealed'&&styles.sealed]}><Text style={styles.badgeText}>{item.kind==='Karte'?'KARTE':'SEALED'}</Text></View><View style={styles.main}><Text style={styles.name}>{item.name}</Text><Text style={styles.meta}>{item.subtitle}</Text></View>{item.marketPrice!=null&&<Text style={styles.price}>{euro(item.marketPrice)}</Text>}</View>)}
  </ScrollView></SafeAreaView>;
}

const styles=StyleSheet.create({safe:{flex:1,backgroundColor:'#050914'},container:{padding:20,paddingBottom:38},kicker:{color:'#66DCF1',fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{color:'#F7F9FF',fontSize:30,fontWeight:'900',marginTop:5},subtitle:{color:'#74819A',marginTop:4,marginBottom:16},summary:{backgroundColor:'#0B1325',borderRadius:20,borderWidth:1,borderColor:'#21305A',padding:16,flexDirection:'row',justifyContent:'space-between',marginBottom:14},summaryLabel:{color:'#697793',fontSize:9,fontWeight:'900',letterSpacing:1},summaryValue:{color:'#7FE4F5',fontWeight:'900',fontSize:22,marginTop:3},summaryPrice:{color:'#D8C7FF',fontWeight:'900',fontSize:18,marginTop:3},empty:{backgroundColor:'#09111F',borderRadius:20,padding:24,borderWidth:1,borderColor:'#192743',alignItems:'center'},heart:{color:'#B060FF',fontSize:38},emptyTitle:{color:'#F2F5FF',fontWeight:'900',fontSize:17,marginTop:5},emptyText:{color:'#74819A',marginTop:6,lineHeight:19,textAlign:'center'},card:{backgroundColor:'#09111F',borderRadius:18,padding:12,flexDirection:'row',alignItems:'center',borderWidth:1,borderColor:'#192743',marginBottom:10},badge:{width:54,height:54,borderRadius:12,backgroundColor:'#0F1D35',borderWidth:1,borderColor:'#2B567E',alignItems:'center',justifyContent:'center'},sealed:{borderColor:'#704AB0'},badgeText:{color:'#87DFF2',fontSize:9,fontWeight:'900'},main:{flex:1,paddingHorizontal:12},name:{color:'#F2F5FF',fontSize:14,fontWeight:'900'},meta:{color:'#74819A',fontSize:11,marginTop:4},price:{color:'#F2F5FF',fontWeight:'900'}});